creation_rules:
  - path_regex: .*/mainnet/overlays/pocket-core-1
    gcp_kms: projects/pocket-core-mainnet/locations/global/keyRings/mainnet/cryptoKeys/node1
  - path_regex: .*/mainnet/overlays/pocket-core-2
    gcp_kms: projects/pocket-core-mainnet/locations/global/keyRings/mainnet/cryptoKeys/node2