apiVersion: v1
data:
  config.json: |
    {
        "tendermint_config": {
            "RootDir": "/home/app/.pocket",
            "ProxyApp": "tcp://127.0.0.1:26658",
            "Moniker": "pocket-core-blockchain",
            "FastSyncMode": true,
            "DBBackend": "cleveldb",
            "DBPath": "data",
            "LogLevel": "*:info, *:error",
            "LogFormat": "plain",
            "Genesis": "config/genesis.json",
            "PrivValidatorKey": "priv_val_key.json",
            "PrivValidatorState": "priv_val_state.json",
            "PrivValidatorListenAddr": "",
            "NodeKey": "node_key.json",
            "ABCI": "socket",
            "ProfListenAddress": "",
            "FilterPeers": false,
            "RPC": {
                "RootDir": "/home/app/.pocket",
                "ListenAddress": "tcp://0.0.0.0:26657",
                "CORSAllowedOrigins": [],
                "CORSAllowedMethods": [
                    "HEAD",
                    "GET",
                    "POST"
                ],
                "CORSAllowedHeaders": [
                    "Origin",
                    "Accept",
                    "Content-Type",
                    "X-Requested-With",
                    "X-Server-Time"
                ],
                "GRPCListenAddress": "",
                "GRPCMaxOpenConnections": 5000,
                "Unsafe": false,
                "MaxOpenConnections": 5000,
                "MaxSubscriptionClients": 1000,
                "MaxSubscriptionsPerClient": 1000,
                "TimeoutBroadcastTxCommit": 10000000000,
                "MaxBodyBytes": 1000000,
                "MaxHeaderBytes": 10485760,
                "TLSCertFile": "",
                "TLSKeyFile": ""
            },
            "P2P": {
                "RootDir": "/home/app/.pocket",
                "ListenAddress": "tcp://0.0.0.0:26656",
                "ExternalAddress": "",
                "Seeds": "03b74fa3c68356bb40d58ecc10129479b159a145@seed1.mainnet.pokt.network:20656,64c91701ea98440bc3674fdb9a99311461cdfd6f@seed2.mainnet.pokt.network:21656",
                "PersistentPeers": "e09ce22e0abfd8129776128c0c9b3836024d8c6e@node1.mainnet.pokt.network:22656,8dd722c42425783b50db707995f841b3c7ccc827@node2.mainnet.pokt.network:23656,8afc6b4195e3fd59fa3aa8bab65b2b7c497cedf9@node3.mainnet.pokt.network:24656,d46556719200aee73fc7446731ae58496978548d@node4.mainnet.pokt.network:25656,5bcae50364952a5fa3a8363f93f2adffc9eff42e@node5.mainnet.pokt.network:26656,a8943929b30cbc3e7a30c2de06b385bcf874134b@node6.mainnet.pokt.network:27656,c6dfe12a4ff2bc2b44c83c791853b6edb6c5eb58@node7.mainnet.pokt.network:28656,913fed2298bc8af74989bc56d94e2e4ca95a6519@node8.mainnet.pokt.network:29656,40c8973967b8d6b1123029819cad20fd44580e9e@node9.mainnet.pokt.network:20756,e74727d0ba34d9f7f6f583cb4a87dbe91d692c5f@node10.mainnet.pokt.network:21756,bf214ae424a4bd698972e4f4fda97939e9909bdd@node11.mainnet.pokt.network:22756, 46ed186385df21121ea279aef2094d2fea79235b@node12.mainnet.pokt.network:23756, 0a9001ee20f796a6f794f882287c032ea8549c3b@node13.mainnet.pokt.network:24756, 32aa0d57bf341b517a5947731b99f4d9387d7d3e@node14.mainnet.pokt.network:25756, a1726dd9509e741169b912675cbfa8de2fe8113c@node15.mainnet.pokt.network:26756, c2c6fb35d9f3f2ea0bc6faa641acf8d348d0fb9e@node16.mainnet.pokt.network:27756, 4dbf149b73dbb3451e4c5b1dab6d1da9bb4086fc@node17.mainnet.pokt.network:21756, 9b95a90092c787f88f06311a3073a9212a610fb6@node18.mainnet.pokt.network:29756, 79d807fdf03c2776082da65f275a610ad1ba2862@node19.mainnet.pokt.network:20856, e2df8f63be18d37cf8258a2bb6800811196a1931@node20.mainnet.pokt.network:21856",
                "UPNP": true,
                "AddrBook": "config/addrbook.json",
                "AddrBookStrict": false,
                "MaxNumInboundPeers": 1000,
                "MaxNumOutboundPeers": 1000,
                "FlushThrottleTimeout": 100000000,
                "MaxPacketMsgPayloadSize": 1024,
                "SendRate": 5120000,
                "RecvRate": 5120000,
                "PexReactor": true,
                "SeedMode": false,
                "PrivatePeerIDs": "",
                "AllowDuplicateIP": true,
                "HandshakeTimeout": 20000000000,
                "DialTimeout": 3000000000,
                "TestDialFail": false,
                "TestFuzz": false,
                "TestFuzzConfig": {
                    "Mode": 0,
                    "MaxDelay": 3000000000,
                    "ProbDropRW": 0.2,
                    "ProbDropConn": 0,
                    "ProbSleep": 0
                }
            },
            "Mempool": {
                "RootDir": "/home/app/.pocket",
                "Recheck": true,
                "Broadcast": true,
                "WalPath": "",
                "Size": 9000,
                "MaxTxsBytes": 1073741824,
                "CacheSize": 9000,
                "MaxTxBytes": 1048576
            },
            "FastSync": {
                "Version": "v0"
            },
            "Consensus": {
                "RootDir": "/home/app/.pocket",
                "WalPath": "data/cs.wal/wal",
                "TimeoutPropose": 60000000000,
                "TimeoutProposeDelta": 10000000000,
                "TimeoutPrevote": 60000000000,
                "TimeoutPrevoteDelta": 10000000000,
                "TimeoutPrecommit": 60000000000,
                "TimeoutPrecommitDelta": 10000000000,
                "TimeoutCommit": 780000000000,
                "SkipTimeoutCommit": false,
                "CreateEmptyBlocks": true,
                "CreateEmptyBlocksInterval": 900000000000,
                "PeerGossipSleepDuration": 100000000,
                "PeerQueryMaj23SleepDuration": 2000000000
            },
            "TxIndex": {
                "Indexer": "kv",
                "IndexTags": "tx.hash,tx.height,message.sender,transfer.recipient",
                "IndexAllTags": false
            },
            "Instrumentation": {
                "Prometheus": false,
                "PrometheusListenAddr": ":26660",
                "MaxOpenConnections": 3,
                "Namespace": "tendermint"
            }
        },
        "pocket_config": {
            "data_dir": "/home/app/.pocket",
            "genesis_file": "genesis.json",
            "chains_name": "chains.json",
            "session_db_type": "cleveldb",
            "session_db_name": "session",
            "evidence_db_type": "cleveldb",
            "evidence_db_name": "pocket_evidence",
            "tendermint_uri": "tcp://localhost:26657",
            "keybase_name": "pocket-keybase",
            "rpc_port": "8081",
            "client_block_sync_allowance": 10,
            "max_evidence_cache_entries": 500,
            "max_session_cache_entries": 500,
            "json_sort_relay_responses": true
        }
    }
kind: ConfigMap
metadata:
  labels:
    app: pocket-core
  name: pocket-core-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pocket-core
  name: pocket-core
spec:
  ports:
  - name: pocket
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tendermint
    port: 26657
    protocol: TCP
    targetPort: 26657
  - name: tendermintpeers
    port: 26656
    protocol: TCP
    targetPort: 26656
  - name: prometheus
    port: 26660
    protocol: TCP
    targetPort: 26660
  selector:
    app: pocket-core
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pocket-core
    persistency: "true"
  name: pocket-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocket-core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pocket-core
        persitency: "true"
    spec:
      containers:
      - args:
        - --datadir=/home/app/.pocket
        - --keybase=false
        - --mainnet
        image: gcr.io/pocket-core-mainnet/mainnet-container:a63e91d
        imagePullPolicy: Always
        name: pocket-core
        ports:
        - containerPort: 26657
          name: tendermint
        - containerPort: 8081
          name: pocket
        - containerPort: 26656
          name: tendermintpeers
        - containerPort: 26660
          name: grafana
        resources:
          requests:
            cpu: 2000m
            memory: 4000Mi
        volumeMounts:
        - mountPath: /home/app/.pocket
          name: pocket-core
      initContainers:
      - command:
        - sh
        - -c
        - mkdir -p /home/app/.pocket/config/ && cp /tmp/*.json /home/app/.pocket/config/
          && echo {} > /home/app/.pocket/priv_val_state.json && echo "Verifying if data folder is not empty. If its not empty, this command exits and resume pocket run" && mkdir -p /home/app/.pocket/data/ && find /home/app/.pocket/data/ -maxdepth 0 -empty -exec echo {} is empty. \; | grep "empty" && echo "Downloading blockchain data" || exit 0 && cd /home/app/.pocket/data &&  gsutil cp  gs://blockchains-data/pocket-network-mainnet-blockchain.tar ./pocket-network-mainnet.tar && echo "Downloaded pocket network blockchain.tar file now decompressing" && tar -xf pocket-network-mainnet.tar && rm  ./pocket-network-mainnet.tar && echo "deleted compressed file .. exiting"
        image: google/cloud-sdk:313.0.0
        name: copy-configs
        volumeMounts:
        - mountPath: /home/app/.pocket
          name: pocket-core
        - mountPath: /tmp
          name: pocket-core-config
      nodeSelector:
        cloud.google.com/gke-nodepool: blockchain-nodes
      restartPolicy: Always
      volumes:
      - name: pocket-core
        persistentVolumeClaim:
          claimName: pocket-core-blockchain-data
      - configMap:
          name: pocket-core-config
        name: pocket-core-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pocket-core-blockchain-data
    persistency: "true"
  name: pocket-core-blockchain-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30G
  storageClassName: pocket-core-blockchain-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocket-core-blockchain-data
spec:
  storageClassName: "pocket-core-blockchain-export"
  capacity:
    storage: 30G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: blockchain
    name: pocket-core-blockchain-data
  gcePersistentDisk:
    pdName: pocket-core-blockchain-data
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pocket-core-blockchain-data
provisioner: pd.csi.storage.gke.io 
allowVolumeExpansion: true
parameters:
  type: pd-balanced
