# kind: PrefixSuffixTransformer
nameSuffix: "-2"
commonLabels:
  app: pocket-core-2
bases:
  - ../../base/


configMapGenerator:
- name: pocket-core-config-2
  files:
  - ../chains.json
  - ./config.json
patchesStrategicMerge:
  - ./patch.yaml
resources:
  - ./node-key-secret.yaml
  - ./priv-val-key-secret.yaml



