apiVersion: ENC[AES256_GCM,data:DK8=,iv:Ol47654ZDaC1p0LT6EQhehqJa9ci3ks+Ic08KHglhPU=,tag:MYmqO+SsGv/O30QfXyJBkg==,type:str]
data:
    priv_val_key.json: ENC[AES256_GCM,data:7S/OujrKdkdbBwraiKzvQRpFH5rumG3mORVHeYykaKtfmNSV5ULolILe9DMrGDPdz2P3h2NiVeVMw1aiGjUTxo0B0sRxskd3A11f0xXe9+5c8dOmEUAH0cRgqjX/JaBL4DGWIZuNW14+09zaI3nOBGWyLFCoibqcH14Ya6o+prXKhimMm5XjcjBUEuxwtO75FJ4EXVQurJ4lEYhN0eSsfasgXqOgmL2Gc7qdjAmY4yjtZ73kj597z6LLO7Fxgiv5Fr6GPHPmgW86geoPyatY582+X0Hkl7ANP+7Ulg0I/VmaxaC6vGgkXJH+Y97ZjWsViztT9oa59kv/l7uXK5uQSjjpJlnz3ibpn1qmt2HEcJqvw1NaR5PpaayJb/ep+Srl1Fx4YX/QY082FuZqqt6n1Gd4PgCUofsm7I5k++JbKmER1BVHC4ZgbuQVNn6ZgVsK0aShmA7OdtDZZRx+kmU5KaSixP2fwSoPFX5w9TIn/LarL54you7nivHlFTrifqU7n25DbwTq5a8/6iBu/L3E90Mg/t5/R4EkX/TWxO18VDO1ZwtS46GH4EllRFbxL/CMPC8AKLVsoHS/PAuARtAmvVEgHcu/gakrA0OY0g==,iv:inDR6TDnTmbPlih80gz0gwLbMtn56CPD7Ileqmld0RM=,tag:1jJ8YsKZNfUkhOFUvcDkew==,type:str]
kind: ENC[AES256_GCM,data:342yvEux,iv:ROTaF5bayxuGANmSb73ji97NEsug6OxxDwzlejTFWOs=,tag:1IglKIc8ZGO/RC1huVzyBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0vE13TNOdNmeyR5EGsjTsfMZLnGT4XUf+g==,iv:+i8HZir+XrCgabE/rgp0LJJ+bOVTqfRpZvk4nyyIyNc=,tag:YiAKI76Q4LLlV+ANfTqYcQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/pocket-core-mainnet/locations/global/keyRings/mainnet/cryptoKeys/node2
        created_at: '2020-12-18T02:19:43Z'
        enc: CiQAsm6t1Z4rKcn3lcNqTuGALOnXT+65FKdTMHof+AL9KXI+szMSSQBDuLgs2yJUGLzZIJttowIkGKUxw/FZmlKEgOVGnDeNI95kJcGZDSTsTJXRY/MFwwsojytH/EvbmT+fRtNDB2lO4nJVh2q1NiU=
    azure_kv: []
    lastmodified: '2020-12-18T02:19:44Z'
    mac: ENC[AES256_GCM,data:3S6UOITIGBWCPeKYeVFyokiVZcm8VxE54P+ccRWwaHVZurbXTT365cGMimLgfn+U/FspMEsSv1Kx7DzX+YJXAp+GMe7F5RmS8r07dsKbsJyzK5U0gCshvkl84PI5dBhYN+3kUOk1imwC/2BzhwocVqgjCwocbzFcfB7UyoYP6QE=,iv:UcI0YmgwxunKzjC+Tynx69duEfs99l0Dwv69USHn82U=,tag:Z7y2Ku94Z0KbPl+4bZNhbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
