# kind: PrefixSuffixTransformer
nameSuffix: "-1"
commonLabels:
  app: pocket-core-1
bases:
  - ../../base/


configMapGenerator:
- name: pocket-core-config-1
  files:
  - ../chains.json
  - ./config.json
patchesStrategicMerge:
  - ./patch.yaml
resources:
  - ./node-key-secret.yaml
  - ./priv-val-key-secret.yaml



