apiVersion: v1
data:
  node_key.json: ewogICJwcml2X2tleSI6IHsKICAgICJ0eXBlIjogInRlbmRlcm1pbnQvUHJpdktleUVkMjU1MTkiLAogICAgInZhbHVlIjogInVvdmdVa0JHUU0vZWI0VjJIb0lZb1JwYXdnWSswMXIvSUFWMTNXamp0QjFxUGZpbGV3Q0QwRUdZWmVSMExSemovSWNHaXk0V1Z1alNEOFpNRUdtVW1RPT0iCiAgfQp9
kind: Secret
metadata:
  name: pocket-core-node-key5
