resources:
  - ./blackbox.yaml
  - ./loki-storageclass.yaml

secretGenerator:
  - name: additional-scrape-configs
    files:
      - ./prometheus-additional.yaml
generatorOptions:
  disableNameSuffixHash: true

namespace: monitoring
