apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-storage 
  labels:
    persistency: "true"
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd
