apiVersion: v1
kind: Service
metadata:
    labels:
        app: pocket-core
    name: pocket-core
spec:
    ports:
      - name: pocket 
        protocol: TCP
        port: 8081
        targetPort: 8081
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8081
      - name: https
        protocol: TCP
        port: 443
        targetPort: 443
      - name: tendermint
        protocol: TCP
        port: 26657
        targetPort: 26657
      - name: tendermintpeers
        protocol: TCP
        port: 26656
        targetPort: 26656
      - name: prometheus 
        protocol: TCP
        port: 26660 
        targetPort: 26660
    type: ClusterIP 
    selector:
        app: pocket-core
