apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-core-data
  labels:
    failure-domain.beta.kubernetes.io/zone: us-east1-b
    persistency: "true"
spec:
  storageClassName: pocket-core
  resources:
    requests:
      storage: 60Gi
  accessModes:
    - ReadWriteOnce
status: {}
